---
- name: Install and start nginx server
  hosts: nginx
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: Start nginx server
      service:
        name: nginx
        state: started
  
